### ISSUE TITLE
Не обрезать твиты до 140 символов при импорте

### ISSUE THREAD

**Issue by MeFoDy** [web-standards-ru/web-standards-up#15]
Сейчас при импорте берутся обрезанные твиты со ссылками на оригинал. Твиттер подрос до 280 символов. Хотелось бы добавлять полный текст из них. Руками редактировать долго, повторять не хочется.

**Comment by pepelsbey** [comment]
@h4 посмотришь? :)

**Comment by h4** [comment]
@MeFoDy погляди, так норм? https://gist.github.com/h4/d8b91025cc54c55b9a884d69e86545d9

**Comment by MeFoDy** [comment]
> @MeFoDy погляди, так норм? https://gist.github.com/h4/d8b91025cc54c55b9a884d69e86545d9

Потрясающе, спасибо! Только не надо обновлять существующий WSD в Питере. Можно перегенерить запись с WSD в Киеве 2018, она с многоточиями.

**Comment by h4** [comment]
В общем, там действительно выяснилось, что Антон Шувалов перестал развивать свой пакет-обёртку для запросов в апи твиттера, пришлось выдерныть все сто с небольшим строк кода к нам в репозиторий. Надо теперь это дело немного в порядок привести и тогда можно будет мержить.

Запись из Киева поправлю, да.
